services:
  namorix:
    build:
      context: .
      dockerfile: Dockerfile
    image: namorix/namorix:latest
    container_name: namorix
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
      - "80:80"
      - "443:443"
    volumes:
      - /home/izerocs/Documents/GitHub/namorix/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Frontgate__GeoIpDatabasePath=/app/GeoLite2-Country.mmdb
    cap_add:
      - NET_BIND_SERVICE
      - NET_ADMIN
