export const NmxIconFontSymbol = {
  SECURITY: "ic-security",
  SEARCH: "ic-search",
  CLOSE: "ic-close",
  MINIMIZE: "ic-minimize",
  MAXIMIZE: "ic-maximize",
  RESTORE: "ic-restore",
  ARROW_PREV: "ic-arrow-prev",
  ARROW_NEXT: "ic-arrow-next",
  ARROW_UP: "ic-arrow-up",
  ARROW_DOWN: "ic-arrow-down",
  ARROW_BAR_UP: "ic-arrow-bar-up",
  ARROW_BAR_DOWN: "ic-arrow-bar-down",
  MENU: "ic-menu",
  MENU_FOLD: "ic-menu-fold",
  LOGS: "ic-logs",
  NODES: "ic-nodes",
  STATS: "ic-stats",
  APPEARANCE: "ic-appearance",
  SETTING: "ic-setting",
  USER: "ic-user",
  LINK: "ic-link",
  EXIT: "ic-exit",
  ENTER: "ic-enter",
  REFRESH: "ic-refresh",
  PLAY: "ic-play",
  PAUSE: "ic-pause",
  CHECK: "ic-check",
  WARNING: "ic-warning",
  INFO: "ic-info",
  NOTIFICATION: "ic-notification",
  DENSITY_COMPACT: "ic-density-compact",
  DENSITY_DEFAULT: "ic-density-default",
  DENSITY_SPACIOUS: "ic-density-spacious",
  MARK_ALL: "ic-mark-all",
  FILTER: "ic-filter",
  DELETE: "ic-delete",
  TIME: "ic-time",
  RAM: "ic-ram",
  CPU: "ic-cpu",
  APPS: "ic-apps",
  UPDATE: "ic-update",
  STOP: "ic-stop",
  INSTALL: "ic-install",
} as const

export type NmxIconFontSymbol =
  (typeof NmxIconFontSymbol)[keyof typeof NmxIconFontSymbol]
